# Generated by Django 2.2.24 on 2021-11-01 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='U1FileUpload',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('category', models.CharField(db_column='CATEGORY', max_length=125)),
                ('file_name', models.CharField(db_column='FILE_NAME', max_length=125)),
                ('issue_date', models.DateField(db_column='ISSUE_DATE')),
                ('expire_date', models.DateField(db_column='EXPIRE_DATE')),
                ('entry_date', models.DateField(db_column='ENTRY_DATE')),
                ('user_id', models.CharField(db_column='USER_ID', max_length=125)),
                ('last_update_date', models.DateField(db_column='LAST_UPDATE_DATE')),
            ],
            options={
                'db_table': 'U1_FILE_UPLOAD',
                'managed': False,
            },
        ),
    ]
