# Generated by Django 2.2.24 on 2021-11-02 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='U1Members',
            fields=[
                ('user_id', models.AutoField(db_column='USER_ID', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='NAME', max_length=50)),
                ('person_id', models.CharField(db_column='PERSON_ID', max_length=50)),
                ('email', models.CharField(db_column='EMAIL', max_length=50)),
                ('status', models.CharField(db_column='STATUS', max_length=50)),
                ('valid_from', models.DateField(db_column='VALID_FROM')),
                ('valid_to', models.DateField(db_column='VALID_TO')),
                ('last_update_date', models.DateField(db_column='LAST_UPDATE_DATE')),
                ('user_level', models.IntegerField(db_column='USER_LEVEL')),
            ],
            options={
                'db_table': 'U1_MEMBERS',
                'managed': False,
            },
        ),
    ]
